###
//  -------------------  Check Routing ------------------------

GET http://localhost:3000/

###
//  -------------------  Get All Tasks  ------------------------

GET http://localhost:3000/task
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjEyMzQ1NiwiaWF0IjoxNjUwMzg4NTU0LCJleHAiOjE2NTAzOTIxNTR9.U3mC_s5fCT7pDXEci5rb71i_tq-lzWRlyDsaIP_iH30
###


//  -------------------  Get Task By Kid ID' ------------------------

GET http://localhost:3000/task/kid
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjEyMzQ1NiwiaWF0IjoxNjUwMzg4NTU0LCJleHAiOjE2NTAzOTIxNTR9.U3mC_s5fCT7pDXEci5rb71i_tq-lzWRlyDsaIP_iH30


###

//  -------------------  Add Tasks ------------------------

POST http://localhost:3000/task
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjVlZTAxNTFhMzEzODAwNDY3ZjQ3Y2MiLCJpYXQiOjE2NTAzODY4MTIsImV4cCI6MTY1MDM5MDQxMn0.oGFYcnVQPJZ_xDLoPm7VS9PfQrMwexksj9HSeBoBBbE
Content-Type: application/json

{
  "kidid": 123456,
  "message": "Do your homework",
  "amount": 150
}



###
//  -------------------  Get All Tasks  ------------------------

GET http://localhost:3000/task
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIzMDY1NDY1IiwiaWF0IjoxNjUwMzg4NzMzLCJleHAiOjE2NTAzOTIzMzN9.ekjQaM7XYa-0WwS3Y70aEdiP1BlEEwjGCwLpxpmEzJg

Content-Type:application/json


###

//  -------------------  Add Transaction ------------------------
POST  http://localhost:3000/transaction
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIzMDY1NDY1IiwiaWF0IjoxNjUwMzkwMjI4LCJleHAiOjE2NTAzOTM4Mjh9.CUhkdXE4H54TD7DYPqs129rZ4gjMU_GIrWtHYTJBWuA
Content-Type:application/json

{   
    "amount": 50,
    "description": "gift for Pesah"
}







//  -------------------  Auth ------------------------
###
//  -------------------  Parent Register ------------------------
POST http://localhost:3000/auth/register
Content-Type: application/json

{   
    "email": "parent@gmail.com",
    "password": "12345"
}

###
//  -------------------  Child Register ------------------------
//  -------------------  Only Fields Diffrence ------------------------

POST http://localhost:3000/auth/register
Content-Type: application/json

{   "_id": "3065465",
    "balance": 300,
    "email": "child@gmail.com",
    "password": "54321"
}

###
//  -------------------  Login ------------------------
//  ------------------- Same API For Both ------------------------


POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "test@gmail11.com",
    "password": "12345"
}


###
//  -------------------  Refresh Token Not implemented Yet ------------------------

POST http://localhost:3000/auth/logout
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIzMDY1NDY1IiwiaWF0IjoxNjUwMzg4NDg1fQ.jcTKF37lauG7FxiIfMQHHftcY6dEEjkuKU64aggbUPU

Content-Type: application/json

{
    "message" : "Check",
    "sender" : "Alon"
}

###
//  -------------------  Refresh Token Not implemented Yet ------------------------

POST http://localhost:3000/auth/refreshtoken
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIzMDY1NDY1IiwiaWF0IjoxNjUwMzg4NDg1fQ.jcTKF37lauG7FxiIfMQHHftcY6dEEjkuKU64aggbUPU
Content-Type: application/json

{
    "message": "Logout",
    "status": 200
}
