###
//  -------------------  Check Routing ----------------------------

GET http://localhost:3000/

###
//  -------------------  Get All Tasks  ----------------------------

GET http://localhost:3000/task
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY5NzZkNzBjOWY0ODBkYWI2NTU1YjEiLCJpYXQiOjE2NTEzNTA3MzQsImV4cCI6MTY1MTM1NDMzNH0.8Lrsb16LEumXua05siBIKTeK35I7Dmtn6w0S0jb2Dbs
###


//  -------------------  Get Task By Kid ID' ------------------------

GET http://localhost:3000/task/kid
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjEyMzQ1NiwiaWF0IjoxNjUxNjU1MDIyLCJleHAiOjE2NTE2NTg2MjJ9.vTGSYU_ukZHNljwuz5Qbmd2gPUZPKN8tD2WTgJ8PpzI


###

//  -------------------  Get Task For Parent ' ------------------------

POST http://localhost:3000/task/parent
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjgyOGE2NTA3N2I1NmI1MWUwZGE3NzQiLCJpYXQiOjE2NTI4MDQ2MDQsImV4cCI6MTY1MjgwODIwNH0.QHLJBuNdye2AJ7Cd8x6iYTD0vXkRIAGToG3YJJiSBXY
Content-Type: application/json

{
  "kidid": 123456
}


###

//-------------------  Add Tasks ------------------------

POST http://localhost:3000/task
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjgyOGE2NTA3N2I1NmI1MWUwZGE3NzQiLCJpYXQiOjE2NTI5MDQxNDEsImV4cCI6MTY1MjkwNzc0MX0.8KUd6bhWz8JiyiOHB1iDooJ_l7R7eOvL4MZGWxr67Cg
Content-Type: application/json

{
  "kidid": 123455,
  "message": "Do your homework2",
  "amount": 150
}

###

//-------------------  Task Completed ------------------------
//-------------------  Need to pass TASK ID FROM GET TASKS AND TOKEN ------------------------

POST http://localhost:3000/task/completed
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjgyOGE2NTA3N2I1NmI1MWUwZGE3NzQiLCJpYXQiOjE2NTI4MTU4NjMsImV4cCI6MTY1MjgxOTQ2M30.A_C4kpBMAtpq4VYClMWBI2-gdHcytt5l1RTINAT4x5Q
Content-Type: application/json

{
  "_id": "62828a82077b56b51e0da779"
}

###

//  -------------------  Task Completed For Parent (Parent Accept)' ------------------------

POST http://localhost:3000/task/parentaccept
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjgyOGE2NTA3N2I1NmI1MWUwZGE3NzQiLCJpYXQiOjE2NTI5MDQxNDEsImV4cCI6MTY1MjkwNzc0MX0.8KUd6bhWz8JiyiOHB1iDooJ_l7R7eOvL4MZGWxr67Cg
Content-Type: application/json

{
  "_id": "6283c8dba8b3e11f822bf133"
}


###
//                           Child                    
//----------------------------------------------------------------
//  -------------------  Add Transaction  ------------------------
POST  http://localhost:3000/child/transactions
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjEyMiwiaWF0IjoxNjUyODY5NDg2LCJleHAiOjE2NTI4NzMwODZ9.yKHThB6LrCkt5-5rZ5_O_t5XCR4IGD71Nx7DnZxv8oA
Content-Type:application/json

{   
    "amount": 280,
    "description": "got back 30 nis for strawberies"
}


###
//  -------------------  Get All Transactions For CHILD  ------------------------

GET http://localhost:3000/child/transactions
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjIwNTk4MjExLCJpYXQiOjE2NTA5OTAxNjMsImV4cCI6MTY1MDk5Mzc2M30.eIJEVwFz58oHz0csFv2b90Wd_rjlWetwwpOBdO4AzFg
Content-Type:application/json


###
//  -------------------  Get All Transactions For Parent  ------------------------
//  -------------------  You need to be logged to parent and give your Childs ID  ------------------------
POST  http://localhost:3000/child/transactions/parent
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjgyOGE2NTA3N2I1NmI1MWUwZGE3NzQiLCJpYXQiOjE2NTI4ODU5NDQsImV4cCI6MTY1Mjg4OTU0NH0.1nVVAHxz7Fovd-NovNuaMqhYgQvBXFiD0sNGX9fslmY
Content-Type:application/json

{
 "id": 1234567
}


###
//  -------------------  Get Balance  ------------------------

GET http://localhost:3000/child/balance
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjIwNTk4MjExLCJpYXQiOjE2NTA5OTAxNjMsImV4cCI6MTY1MDk5Mzc2M30.eIJEVwFz58oHz0csFv2b90Wd_rjlWetwwpOBdO4AzFg
Content-Type:application/json


###
//  -------------------  Send Money From Parent  ------------------------

post http://localhost:3000/child/sendmoney
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjgyOGE2NTA3N2I1NmI1MWUwZGE3NzQiLCJpYXQiOjE2NTI4NjY3MDYsImV4cCI6MTY1Mjg3MDMwNn0.3Y8J5XMCdY9MNYzI_YgC0K8Fg15UgQ5KYcysNuPKNto
Content-Type:application/json

{
 "_id": 123455,
 "description": "Gift",
 "amount": 125
}


###
//  -------------------      Auth   ------------------------
//
//  -------------------  Parent Register ------------------------
POST http://localhost:3000/auth/register
Content-Type: application/json

{   
    "email": "alon@gmail.com",
    "password": "12345",
    "name": "NISIM"
}

###
//  -------------------  Child Register ------------------------


POST http://localhost:3000/auth/register/child
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjgyOGE2NTA3N2I1NmI1MWUwZGE3NzQiLCJpYXQiOjE2NTI4NjY3MDYsImV4cCI6MTY1Mjg3MDMwNn0.3Y8J5XMCdY9MNYzI_YgC0K8Fg15UgQ5KYcysNuPKNto
Content-Type: application/json

{   
    "_id": 122,
    "name": "Child3",
    "balance": 300,
    "email": "1@gmail.com",
    "password": "12345"
}

###
//  -------------------  Login ------------------------
//  ------------------- Same API For Both ------------------------


POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "is_child": true,
    "email": "1@gmail.com",
    "password": "12345"
}


###
//  -------------------  Logout: Same for both Parent and Child ------------------------

POST http://localhost:3000/auth/logout
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjgyOGE2NTA3N2I1NmI1MWUwZGE3NzQiLCJpYXQiOjE2NTI4MTI5MjR9.YvHvlHjwIMZUBUjp89HoDeU3DRy1iEiX88BjMEbUO7w
Content-Type: application/json

{
    "message" : "Check",
    "sender" : "Alon"
}

###
//  -------------------  Refresh Token Not implemented Yet ------------------------

POST http://localhost:3000/auth/refreshtoken
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjgyOGE2NTA3N2I1NmI1MWUwZGE3NzQiLCJpYXQiOjE2NTI4MTMyOTh9.lmB1seYA1dNyfDS8tYpiTMSh9a0o1Y3fXwNR5v1CdRA
Content-Type: application/json

{
    "message": "Logout",
    "status": 200
}

###
//  -------------------  Linking Parent to KIDS ------------------------
//  -------------------  You must be logged in to parent(authenticated)  ------------------------
//  -------------------  Get All kids for the logged parent ------------------------
GET http://localhost:3000/link
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjgyOGE2NTA3N2I1NmI1MWUwZGE3NzQiLCJpYXQiOjE2NTI4Nzk1MzUsImV4cCI6MTY1Mjg4MzEzNX0.pGLjql76oVHIa76vp9LmhqJUusIcjpFPLc6lZoEDE_Q
Content-Type: application/json


###
//  -------------------  ADD KID API for the logged parent ------------------------

POST http://localhost:3000/link
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjVlZTNkY2VmMjA3YzEwOTkzY2FiZGUiLCJpYXQiOjE2NTA3MDUyNDUsImV4cCI6MTY1MDcwODg0NX0.rapjdclfK4K3o3uKYGL6RsQJd7JVqix0s9T5RGHNS3E
Content-Type: application/json

{
    "id": "1234561"
}

###
//  ------------------- Add Request API ------------------------
//  ------------------- You must be logged in to kid(authenticated) ------------------------


POST http://localhost:3000/request
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjEyMiwiaWF0IjoxNjUyOTc3Mjg2LCJleHAiOjE2NTI5ODA4ODZ9.yEzwDjZDzBWmmwuZ9nHXqXYdwiv2eQv9f1fL1VQRtWE
Content-Type: application/json

{
    "amount": 1256,
    "message": "Need for food"
}


###
//  -------------------  Request GetParent API ------------------------
//  -------------------  Token And KIDID ------------------------
POST http://localhost:3000/request/getparent
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjEyMiwiaWF0IjoxNjUyOTc3Mjg2LCJleHAiOjE2NTI5ODA4ODZ9.yEzwDjZDzBWmmwuZ9nHXqXYdwiv2eQv9f1fL1VQRtWE
Content-Type: application/json

{
    "_id": 1223
}

###
//  -------------------  Delete Request API ------------------------
//  -------------------  Token And taskID ------------------------
POST http://localhost:3000/request/delete
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjEyMiwiaWF0IjoxNjUyOTgxMjUyLCJleHAiOjE2NTI5ODQ4NTJ9.nbsLnYB4tLlGLhMTRGueeEyeK5ovxoozreT3kr5vNaI
Content-Type: application/json

{
    "_id": "62866ea584af80b9c33b1d86"
}

###
//  -------------------  Accept Request API ------------------------
//  -------------------  Token And taskID ------------------------
POST http://localhost:3000/request/accept
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjEyMiwiaWF0IjoxNjUzMDQwMDUxLCJleHAiOjE2NTMwNDM2NTF9.tr0VAgD7k6RH0mDv0TDHqaPHW4P8DKZIfJP_J-YoUw4
Content-Type: application/json

{
    "_id": "6286715f6bd0f337e7afbf3b"
}

